* Custom Google Ngrams Search

The [[https://books.google.com/ngrams][Google Ngrams Viewer]] is really neat. You can use it to compare the frequency of certain terms in millions of books across a timeseries of centuries.

But what if you have an advanced use-case, or run up against limitations in the Google interface? For example, maybe you want to:

 - Search for /bear/ as a noun (i.e. the animal) instead of /bear/ as a verb (i.e. to endure).
 - Search for expressions where one word is unknown, like "capable of ___ing," and fill in the blanks with all possible responses.
 - Do a regular expression search.

* CLI Usage

You can run this yourself if you have lots of space free on your machine.

1. Make sure you have [[https://nixos.org/][the Nix package manager]] installed. On Linux or MacOS, you can usually do this with

#+BEGIN_SRC sh
$ sh <(curl https://nixos.org/nix/install)
#+END_SRC

Then run:

#+BEGIN_SRC sh
nix-shell
#+END_SRC

2. Download the data from Google, using the download script:

#+BEGIN_SRC sh
cd src
runhaskell DownloadData
#+END_SRC

There are a lot of very big files. Not only are the gzipped files hude, but you will need 3GB of space free per gzip file, for the database. That results in a ~140GB database file, just for unigrams and bigrams.

2. Generate the database:

#+BEGIN_SRC sh
runhaskell DB
#+END_SRC

3. Or, run the regex-based script:

#+BEGIN_SRC sh
# From the project root directory
nix-shell --run "cabal run custom-ngrams-search -- -q searchTerm"
#+END_SRC
